Completed the Event Summary Section
0xJamin/cmfest-v1 pull request #10
Opened 2023-07-10 15:43 UTC by Matthewokiemute

2023-07-10 15:57 UTC, 0xJamin requested changes
Remove `.yarn` folder

2023-07-11 12:24 UTC, 0xJamin requested changes

2023-07-11 12:24 UTC, 0xJamin commented on public/images/cm8.png
This image is already in the CMS no need for it here

2023-07-11 12:24 UTC, 0xJamin commented on types.d.ts
> +//Storyblok EventSummary Section
This comment is not needed

2023-07-11 12:24 UTC, 0xJamin commented on types.d.ts
> +type EventSummaryType = StoryblokBlok<"section_event_summary"> & {
This data structure is incorrect, please check the CMS for the correct one and describe the data accordingly

2023-07-11 12:24 UTC, 0xJamin commented on yarn.lock
why does your `yarn.lock` file has so many changes?

2023-07-11 12:25 UTC, 0xJamin commented
@Matthewokiemute why can't you use the data from Storyblok?🤔

2023-07-11 12:31 UTC, Matthewokiemute commented on yarn.lock
I don't have any idea about that

It updated when I ran "yarn install"

2023-07-11 12:42 UTC, Matthewokiemute commented on components/sections/EventSummary/EventSummary.tsx
> +  const { topics, sponsors, summary } = blok;
I tried it nothing will show as the content

That's why I removed them

Maybe if I add them you are the one to connect the contents to the from the StoryBlok CMS

2023-07-11 12:42 UTC, Matthewokiemute commented on components/sections/EventSummary/EventSummary.tsx
> +        <p className="ml-6 text-lg">Sponsors</p>
Okay Changed them

2023-07-11 12:44 UTC, Matthewokiemute commented on .yarnrc.yml
> +nodeLinker: node-modules
Okay sir

2023-07-11 13:08 UTC, 0xJamin commented on components/sections/EventSummary/EventSummary.tsx
> +  const { topics, sponsors, summary } = blok;
<img width="712" alt="Screenshot 2023-07-11 at 2 05 50 PM" src="https://github.com/0xJamin/cmfest-v1/assets/34829458/f8f74437-322d-4764-b045-35e800a253ae">
@Matthewokiemute  Just checked your component and see the data received as props, you mean you can't display this data on the UI?

2023-07-11 13:10 UTC, 0xJamin requested changes

2023-07-11 13:10 UTC, 0xJamin commented on components/sections/EventSummary/EventSummary.tsx
> +          src={cm8}
Images as well are also on the CMS, please use them too

2023-07-20 12:50 UTC, closed without merging