feat: add sponsors-section
0xJamin/cmfest-v1 pull request #13
Opened 2023-07-26 21:05 UTC by eazycodinz

I just added a new feature, the sponsors-section to the project. i also deleted the team image from the image folder.

2023-07-27 00:29 UTC, 0xJamin requested changes

2023-07-27 00:29 UTC, 0xJamin commented on components/sections/SponsorsSection/SponsorsSection.tsx
> +        <div className="grid grid-cols-3 gap-4 justify-items-center md:px-20 px-10">
use `grid-cols-2` for tablets and mobile views

2023-07-27 00:30 UTC, 0xJamin commented on components/sections/SponsorsSection/SponsorsSection.tsx
> +export function SponsorsSection() {
`SponsorSection`

2023-07-27 01:06 UTC, eazycodinz commented on components/sections/SponsorsSection/SponsorsSection.tsx
> +        <div className="grid grid-cols-3 gap-4 justify-items-center md:px-20 px-10">
resolved

2023-07-27 01:07 UTC, eazycodinz commented on components/sections/SponsorsSection/SponsorsSection.tsx
> +export function SponsorsSection() {
resolved

2023-07-27 01:08 UTC, eazycodinz commented on components/sections/SponsorsSection/SponsorsSection.tsx
> +export function SponsorsSection() {
renamed the section from SponsorsSection to SponsorSection

2023-07-27 01:10 UTC, eazycodinz commented on components/sections/SponsorsSection/SponsorsSection.tsx
> +        <div className="grid grid-cols-3 gap-4 justify-items-center md:px-20 px-10">
fixed the responsiveness of the SponsorSection by adding grid-cols-2 for tablets and mobile views.

2023-07-27 01:15 UTC, 0xJamin requested changes

2023-07-27 01:15 UTC, 0xJamin commented on components/sections/SponsorSection/SponsorSection.tsx
> +            <img className="md:w-52 w-36 md:h-12 " src={Image3.src} alt="" />
@eazycodinz add some padding and margin between the sponsors

2023-07-28 12:53 UTC, 0xJamin requested changes

2023-07-31 12:27 UTC, 0xJamin approved these changes
Looks good @eazycodinz  well done

2023-07-31 12:29 UTC, merged