feat: add speakers-section.
0xJamin/cmfest-v1 pull request #16
Opened 2023-08-01 19:38 UTC by eazycodinz

I added a new feature: SpeakersSection to the project, using the images in the image folder, I also deleted the sponsor's image from the image folder since the sponsor image is been mapped from the CMS.

2023-08-02 01:24 UTC, eazycodinz commented
I modified the speaker section, deleted the images from the image folder, and map the image from the CMS,

2023-08-03 10:46 UTC, 0xJamin requested changes
<img width="602" alt="Screenshot 2023-08-03 at 11 38 45 AM" src="https://github.com/0xJamin/cmfest-v1/assets/34829458/a09f956f-1c61-45d3-a14a-39525a5e984f">

@eazycodinz some this is how you speaker section looks like, can we fix it?

2023-08-03 10:46 UTC, 0xJamin commented on components/sections/SpearkersSection/SpeakersSection.tsx
> +  console.log(blok);
Remove console.log

2023-08-03 10:46 UTC, 0xJamin commented on types.d.ts
>  type StoryblokImage = {
This is a wrong type declaration, images are not supposed to have role, image and name properties

2023-08-03 10:46 UTC, 0xJamin commented on components/sections/SpearkersSection/SpeakersSection.tsx
> +              <div className="absolute bottom-5 left-2 font-semibold md:text-base text-sm">
why is the position of this text set to absolute? 🤔

2023-08-03 18:43 UTC, 0xJamin commented on types.d.ts
> +  speakers: StoryblokImage[];
```
type SpeakersType = StoryblokBlok<"section_speakers"> & {
heading: string;
speakers: Speaker[];
cta_buttons: Elemmjomfodfodsf

}
```

2023-08-03 18:43 UTC, 0xJamin commented on types.d.ts
> +  name: string;
remove this

2023-08-05 02:55 UTC, eazycodinz commented on components/sections/SpearkersSection/SpeakersSection.tsx
> +  console.log(blok);
The image text has been fixed and the console.log removed.

2023-08-05 02:56 UTC, eazycodinz commented on components/sections/SpearkersSection/SpeakersSection.tsx
> +              <div className="absolute bottom-5 left-2 font-semibold md:text-base text-sm">
the absolute position have been fixed

2023-08-05 02:57 UTC, eazycodinz commented on types.d.ts
> +  speakers: StoryblokImage[];
the type declaration have been refactored.

2023-08-05 02:58 UTC, eazycodinz commented on types.d.ts
> +  name: string;
it has been removed

2023-08-05 03:00 UTC, eazycodinz commented
I refactored the type declaration, and the image text was fixed, the console.log was also removed,

2023-08-06 11:11 UTC, 0xJamin approved these changes
Good Job @eazycodinz , Well done🎉

2023-08-06 11:55 UTC, merged